import type {NextRequest} from 'next/server';
import {collections} from '@/lib/db';
import {verifyEmailVerificationToken} from '@/actions/auth/jwt';

/**
 * Verifies a user's email address from the link sent by the signup workflow.
 *
 * GET /api/verify-email?token=<emailVerificationToken>
 *
 * The token is the JWT generated by the signup workflow (its 24h expiry
 * lives inside the token itself). On success the user document is marked
 * `emailVerified: true` and the stored token is cleared. The endpoint is
 * idempotent: re-clicking a link for an already-verified account returns
 * 200 instead of an error.
 */
export async function GET(request: NextRequest) {
  const token = request.nextUrl.searchParams.get('token');

  if (!token) {
    return Response.json({message: 'Missing token.'}, {status: 400});
  }

  // Reject malformed / expired / forged tokens before touching the database.
  const payload = await verifyEmailVerificationToken(token);
  if (!payload) {
    return Response.json({message: 'Invalid or expired token.'}, {status: 401});
  }

  const user = await collections.users.findOne({emailVerificationToken: token});

  if (!user) {
    // The stored token is gone (already used). If the account is verified,
    // treat this as a benign re-click of the verification link.
    const alreadyVerified = await collections.users.findOne({
      id: payload.userId,
      emailVerified: true,
    });
    if (alreadyVerified) {
      return Response.json({message: 'Email is already verified.'});
    }
    return Response.json({message: 'Invalid or expired token.'}, {status: 401});
  }

  if (user.emailVerified) {
    return Response.json({message: 'Email is already verified.'});
  }

  // Verify atomically: match on the exact stored token so concurrent
  // requests can't double-apply or verify with a rotated token.
  const result = await collections.users.updateOne(
    {id: user.id, emailVerificationToken: token},
    {$set: {emailVerified: true}, $unset: {emailVerificationToken: ''}},
  );

  if (result.matchedCount === 0) {
    return Response.json({message: 'Invalid or expired token.'}, {status: 401});
  }

  return Response.json({message: 'Email verified successfully.'});
}